//------------------------------------------------------------------------------
//
// Опции настройки компиляции
//
//------------------------------------------------------------------------------

// определяем режим ДЕБАГ
//  Позволяет просматривать лог событий в отдельном окне из IDE
//  View -> IDE Internals -> [eventLog] lazExt_aBTF_ObjectInspector
{.$define lazExt_aBTF_ObjectInspector_EventLOG_mode}
{$define in0k_LazarusIdeEXT__DEBUG}

// АвтоOткрытие окна "Object Inspector".
{.$define in0k_lazarusIdePLG__wndSatellite_ObjectInspector__AUTO_SHOW}


